config/routes.rb
Rails.application.routes.draw do
  resources :todos
  get '/todos/:id/complete', to: 'todos#complete'
  get '/todos/list/', to: 'todos#list'
  root 'todos#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
	validates :description, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :complete, :destroy]


  def index
    @todos = Todo.all
  end

  def show
  end


  def new
    @todo = Todo.new
  end

  def edit
  end


  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def complete

    @completed = params[:completed]
    @completed = true
    @completed.save
    respond_to do |format|
      format.html { render :index }
    end

    
  end

    def list
      @todos = Todo.all
    end

  private
   
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:todo)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script type="text/javascript" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  	<script type="text/javascript" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar', todo: @todo %>
    <br>
    <br>
    <%= yield %>
  </body>

  <script
    src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
	 integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E="
	 crossorigin="anonymous">
  </script>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :todo %>
    <%= form.text_field :todo, id: :todo_todo %>


  </div>

    <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>


  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  
  <%= link_to 'Home', todos_path, class:"navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        
        <%= link_to 'List', todos_list_path, class:"nav-link" %> 
        <span class="sr-only">(current)</span>

      </li>
      <li class="nav-item">
        
        <%= link_to 'New Todo', new_todo_path, class:"nav-link" %>

      </li>

    </ul>
  </div>
</nav>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>To Dos</h1>

<h5>Listado:</h5>
  <% @todos.each do |todo| %>
  <div class="row">

        <div class="well col-md-8"><%= todo.todo %></div>
        <button class="btn btn-success btn-xs"><%= link_to 'Show', todo %></button> 
        <button class="btn btn-info btn-xs"><%= link_to 'Edit', edit_todo_path(todo) %></button>
        <button class="btn btn-warning btn-xs"><%= link_to 'Destroy', todo, method: :delete, data: { confirm: '¿Estás seguro de eliminar esta tarea?' } %></button>

        <%= check_box_tag(:completed) %>
        <%= label_tag(:completed, "Tarea Completada") %>

  </div>      
  <% end %>
  

app/views/todos/list.html.erb
<p id="notice"><%= notice %></p>

<h1>To Dos</h1>

<h5>Listado:</h5>

<div class="row">
	
	<div class="col-md-6">
		<% @todos.each do |t| %>
  			<% if t.completed? %>
  				<li> <=% t.description %></li>
  		<% end %> 
  	</div>
  	<div class="col-md-6">
		<% @todos.each do |t| %>
  			<% if !t.completed? %>
  				<li> <=% t.description %></li> 
  		<% end %>
  	</div>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Todo:</strong>
  <%= @todo.todo %>
  <%= check_box_tag(:completed) %>
  <%= label_tag(:completed, "Tarea Completada") %>
  
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>